spring.application.name=discografia

spring.data.mongodb.uri=mongodb+srv://SimonElGranBaron:Simonalonso17@cluster0.iw6f6d5.mongodb.net/discografica-db?retryWrites=true&w=majority&appName=Cluster0

server.port=8080